services:
  - type: web
    name: bpchatgpt-backend
    env: node
    plan: starter
    buildCommand: cd backend && npm ci
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        fromService:
          type: web
          name: bpchatgpt-backend
          property: port
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_KEY
        sync: false
    healthCheckPath: /health